title: Muchen Sun / 孙沐琛
url: "https://muchensun.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Curriculum Vitae"
   link: "/CurriculumVitae/MuchenSun_CurriculumVitae.pdf"
 - name: "GitHub"
   link: "https://github.com/MuchenSun/"
 - name: "Blog"
   link: "blog"
