title: Muchen Sun / 孙沐琛
url: "https://muchensun.github.io"
baseurl: ""

markdown: kramdown
ins_logo: #"./Northwestern_purple_RGB.svg"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "/CurriculumVitae/MuchenSun_CurriculumVitae.pdf"
 - name: "GitHub"
   link: "https://github.com/MuchenSun/"
 - name: "Linkedin"
   link: "https://www.linkedin.com/in/muchen-sun-4089a7158/"
 - name: "Blog"
   link: "blog"
